---
- name: Add CentOS 6.7 repo
  template: src=CentOS67-nss-downgrade.repo dest=/etc/yum.repos.d/CentOS67-nss-downgrade.repo backup=yes owner=root mode=0644

- name: Downgrade NSS packages
  shell: 'yum -y --enablerepo=centos67-nss-downgrade downgrade nss*'

- name: Check yum exclusion
  shell: 'egrep -i "^[[:space:]]*exclude" /etc/yum.conf'
  register: yum_exclude
  ignore_errors: True

- name: Exclude nss from updates
  lineinfile: dest=/etc/yum.conf
              regexp='(?i)(^\s*exclude\s*=(\s*(?!nss)[\w=\-\*]+)*)\s*$'
              line='\1 nss*'
              backrefs=True
              backup=yes

- name: Add Exclude line if doesn't exist
  lineinfile: dest=/etc/yum.conf
              line='Exclude=nss*'
  when: yum_exclude|failed