---
- name: Check if affected
  command: '/usr/bin/curl --connect-timeout 60 -I https://google.com'
  register: nss_affected
  ignore_errors: True

- name: Downgrade NSS
  include: downgrade.yml
  when: nss_affected.rc == -4 and nss_affected.stderr == ""